rm(list = setdiff(ls(), "data_bk"))
gc()
library(arrow)
library(fixest)
library(ggplot2)
library(parallel)
library(DescTools)
library(reshape2)
library(tictoc)
library(haven)
library(rstudioapi)
options(scipen = 10)
library(showtext)
library(arrow)
library(sandwich)
showtext_auto()
library(future)
library(future.apply)
library(stringr)
library(lubridate)
library(fs)
library(readr)
library(dplyr)
library(data.table)
nc <- detectCores() - 2
