---
author: ""
header-includes:
   - \usepackage{rotating}
   - \usepackage{float}
   - \usepackage{natbib}
   - \usepackage{booktabs}
geometry: "left=2cm,right=2cm,top=2.9cm,bottom=1.2cm"
output: 
  pdf_document:
    keep_tex: true
    number_sections: true
# bibliography: crossmom.bib
link-citations: yes

---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>
```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(rio)
library(latex2exp)
library(dplyr)
library(tibble)
library(ggplot2)
library(lubridate)
library(data.table)
library(knitr)
library(kableExtra)
library(haven)
library(tidyr)
library(tidyverse)
library(stargazer, quietly = TRUE)
library(plm) 
library(xtable)
library(RColorBrewer)
library(ggrepel)
library(ggpmisc)
library(scales)
library(sandwich)
library(lmtest)
library(data.table)
library(gtools)
library(sjlabelled)
library(pracma)
library(fs)
library(reshape)
library(reshape2)
library(parallel)
library(this.path)
```
\section{Total}
\subsection{Adjust}
```{r, echo = FALSE, results = 'asis', warning=FALSE, message=FALSE, fig.width = 8, fig.height = 6}
rm(list = ls())
options(xtable.comment = FALSE)
setwd(this.path::this.dir())
for (stock_base in c("all", "large")){
  df_left <- readRDS(paste0('../../tmp/covliquidity/', stock_base, '/pairwise_decom_table.Rds')) %>%
    dplyr::filter(micro == "yes",
                  name == "lev",
                  liq_measure == "minus_spread",
                  part == "total",
                  parameter != "t_per") %>%
    dplyr::select(-micro, -name, -liq_measure, -part) %>%
    dplyr::mutate(group_id = case_when(var == "combined"~1,
                                       var == "Indu"~2,
                                       var == "BEAcustomer"~3,
                                       var == "BEAsupplier"~4,
                                       var == "Tec"~5,
                                       var == "Geo"~6,
                                       var == "Pseudo"~7,
                                       var == "Econ"~8,
                                       var == "Analyst"~9)) %>%
    dplyr::arrange(group_id, parameter) %>%
    dplyr::select(-group_id) 
  
  df_right <- readRDS(paste0('../../tmp/covliquidity/', stock_base, '/pairwise_decom_table.Rds')) %>%
    dplyr::filter(micro == "yes",
                  name == "lev",
                  liq_measure == "volume",
                  part == "total",
                  parameter != "t_per") %>%
    dplyr::select(-micro, -name, -liq_measure, -part) %>%
    dplyr::mutate(group_id = case_when(var == "combined"~1,
                                       var == "Indu"~2,
                                       var == "BEAcustomer"~3,
                                       var == "BEAsupplier"~4,
                                       var == "Tec"~5,
                                       var == "Geo"~6,
                                       var == "Pseudo"~7,
                                       var == "Econ"~8,
                                       var == "Analyst"~9)) %>%
    dplyr::arrange(group_id, parameter) %>%
    dplyr::select(-group_id) 
  
  df.1 <- df_left %>%
    dplyr::inner_join(df_right, by = c("var", "parameter")) %>%
    dplyr::group_by(var) %>% 
    dplyr::mutate(var = replace(var, row_number() != 1, NA)) %>%
    dplyr::ungroup() 
  
  
  
  
  
  
  data_table <- df.1 %>%
    dplyr::select(-parameter)
    
  
  align_vactor <- paste0("ll", paste0(rep("c", times = dim(data_table)[2] - 1), collapse = ""))
  caption_name_15 <- paste0("Decompose $R'_{t+1}\\cdot\\Pi_t\\cdot R_{t}$ Based on Pairwise Liquidity Comparison")
  x.side <- xtable(data_table, align = align_vactor, caption = caption_name_15)
  cat("The stock base is:", stock_base)
  print(x.side, type = "latex", table.placement = "H", include.rownames = FALSE,
        include.colnames = FALSE, scalebox = 0.9,
            caption.placement = "top", #"top", NULL
            hline.after=NULL, #We don't need hline; we use booktabs
            floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
            sanitize.text.function = force , # Important to treat content of first column as latex function
             add.to.row = list(pos = list(-1, 
                                            nrow(data_table)),
                               command = c(paste("\\hline \n",  # NEW row
                                                 "Liq measure:&\\multicolumn{5}{c}{\\textbf{Bid-ask spread}}
                                                 & \\multicolumn{5}{c}{\\textbf{Trading Volume}}
                                                 \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n",
                                                 " & All& Illiq$\\rightarrow$Liq & Self &Liq$\\rightarrow$illiq  & Diff & All& Illiq$\\rightarrow$Liq & Self & Liq$\\rightarrow$illiq & Diff  \\\\\n",
                                                 "& (1) & (2) & (3) & (4)& (5) & (6) & (7) & (8)& (9) & (10)  \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n"),
                   paste("\\hline \n"))
                   )
  )
  
  out_dir <- paste0(stock_base, "/")
  dir_create(out_dir, showWarnings = FALSE, recursive = TRUE)
  
  print(x.side, type = "latex", table.placement = "H", include.rownames = FALSE,
        include.colnames = FALSE, scalebox = 0.9,
            caption.placement = "top", #"top", NULL
            hline.after=NULL, #We don't need hline; we use booktabs
            floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
            sanitize.text.function = force , # Important to treat content of first column as latex function
             add.to.row = list(pos = list(-1, 
                                            nrow(data_table)),
                               command = c(paste("\\hline \n",  # NEW row
                                                 "Liq measure:&\\multicolumn{5}{c}{\\textbf{Bid-ask spread}}
                                                 & \\multicolumn{5}{c}{\\textbf{Trading Volume}}
                                                 \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n",
                                                 " & All& Illiq$\\rightarrow$Liq & Self &Liq$\\rightarrow$illiq  & Diff & All& Illiq$\\rightarrow$Liq & Self & Liq$\\rightarrow$illiq & Diff  \\\\\n",
                                                 "& (1) & (2) & (3) & (4)& (5) & (6) & (7) & (8)& (9) & (10)  \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n"),
                   paste("\\hline \n"))),
        file = paste0(stock_base, "/liquid_illiquid_total_lev_adjust.tex")
  )
}
```
\newpage
\section{Asy}
\subsection{Adjust}
```{r, echo = FALSE, results = 'asis', warning=FALSE, message=FALSE, fig.width = 8, fig.height = 6}
rm(list = ls())
options(xtable.comment = FALSE)
setwd(this.path::this.dir())
for (stock_base in c("all", "large")){
  df_left <- readRDS(paste0('../../tmp/covliquidity/', stock_base, '/pairwise_decom_table.Rds')) %>%
    dplyr::filter(micro == "yes",
                  name == "lev",
                  liq_measure == "minus_spread",
                  part == "asy",
                  parameter != "t_per") %>%
    dplyr::select(-micro, -name, -liq_measure, -part) %>%
    dplyr::mutate(group_id = case_when(var == "combined"~1,
                                       var == "Indu"~2,
                                       var == "BEAcustomer"~3,
                                       var == "BEAsupplier"~4,
                                       var == "Tec"~5,
                                       var == "Geo"~6,
                                       var == "Pseudo"~7,
                                       var == "Econ"~8,
                                       var == "Analyst"~9)) %>%
    dplyr::arrange(group_id, parameter) %>%
    dplyr::select(-group_id)
  
  df_right <- readRDS(paste0('../../tmp/covliquidity/', stock_base, '/pairwise_decom_table.Rds')) %>%
    dplyr::filter(micro == "yes",
                  name == "lev",
                  liq_measure == "volume",
                  part == "asy",
                  parameter != "t_per") %>%
    dplyr::select(-micro, -name, -liq_measure, -part) %>%
    dplyr::mutate(group_id = case_when(var == "combined"~1,
                                       var == "Indu"~2,
                                       var == "BEAcustomer"~3,
                                       var == "BEAsupplier"~4,
                                       var == "Tec"~5,
                                       var == "Geo"~6,
                                       var == "Pseudo"~7,
                                       var == "Econ"~8,
                                       var == "Analyst"~9)) %>%
    dplyr::arrange(group_id, parameter) %>%
    dplyr::select(-group_id)
  
  df.1 <- df_left %>%
    dplyr::inner_join(df_right, by = c("var", "parameter")) %>%
    dplyr::group_by(var) %>%
    dplyr::mutate(var = replace(var, row_number() != 1, NA)) %>%
    dplyr::ungroup()
  
  
  
  
  
  
  data_table <- df.1 %>%
    dplyr::select(-parameter)
  
  
  align_vactor <- paste0("ll", paste0(rep("c", times = dim(data_table)[2] - 1), collapse = ""))
  caption_name_15 <- paste0("Decompose $R'_{t+1}\\cdot\\Pi_t\\cdot R_{t}$ Based on Pairwise Liquidity Comparison")
  x.side <- xtable(data_table, align = align_vactor, caption = caption_name_15)
  cat("The stock base is:", stock_base)
  print(x.side, type = "latex", table.placement = "H", include.rownames = FALSE,
        include.colnames = FALSE, scalebox = 0.9,
            caption.placement = "top", #"top", NULL
            hline.after=NULL, #We don't need hline; we use booktabs
            floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
            sanitize.text.function = force , # Important to treat content of first column as latex function
             add.to.row = list(pos = list(-1,
                                            nrow(data_table)),
                               command = c(paste("\\hline \n",  # NEW row
                                                 "Liq measure:&\\multicolumn{5}{c}{\\textbf{Bid-ask spread}}
                                                 & \\multicolumn{5}{c}{\\textbf{Trading Volume}}
                                                 \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n",
                                                 " & All& Illiq$\\rightarrow$Liq & Self &Liq$\\rightarrow$illiq  & Diff & All& Illiq$\\rightarrow$Liq & Self & Liq$\\rightarrow$illiq & Diff  \\\\\n",
                                                 "& (1) & (2) & (3) & (4)& (5) & (6) & (7) & (8)& (9) & (10)  \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n"),
                   paste("\\hline \n"))
                   )
  )
  
  print(x.side, type = "latex", table.placement = "H", include.rownames = FALSE,
        include.colnames = FALSE, scalebox = 0.9,
            caption.placement = "top", #"top", NULL
            hline.after=NULL, #We don't need hline; we use booktabs
            floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
            sanitize.text.function = force , # Important to treat content of first column as latex function
             add.to.row = list(pos = list(-1,
                                            nrow(data_table)),
                               command = c(paste("\\hline \n",  # NEW row
                                                 "Liq measure:&\\multicolumn{5}{c}{\\textbf{Bid-ask spread}}
                                                 & \\multicolumn{5}{c}{\\textbf{Trading Volume}}
                                                 \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n",
                                                 " & All& Illiq$\\rightarrow$Liq & Self &Liq$\\rightarrow$illiq  & Diff & All& Illiq$\\rightarrow$Liq & Self & Liq$\\rightarrow$illiq & Diff  \\\\\n",
                                                 "& (1) & (2) & (3) & (4)& (5) & (6) & (7) & (8)& (9) & (10)  \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n"),
                   paste("\\hline \n"))
                   ),
        file = paste0(stock_base, "/liquid_illiquid_asy_lev_adjust.tex")
  )
}
```

\newpage
\section{Sym}


\subsection{Adjust}
```{r, echo = FALSE, results = 'asis', warning=FALSE, message=FALSE, fig.width = 8, fig.height = 6}
rm(list = ls())
options(xtable.comment = FALSE)
setwd(this.path::this.dir())
for (stock_base in c("all", "large")){
  df_left <- readRDS(paste0('../../tmp/covliquidity/', stock_base, '/pairwise_decom_table.Rds')) %>%
    dplyr::filter(micro == "yes",
                  name == "lev",
                  liq_measure == "minus_spread",
                  part == "sym",
                  parameter != "t_per") %>%
    dplyr::select(-micro, -name, -liq_measure, -part) %>%
    dplyr::mutate(group_id = case_when(var == "combined"~1,
                                       var == "Indu"~2,
                                       var == "BEAcustomer"~3,
                                       var == "BEAsupplier"~4,
                                       var == "Tec"~5,
                                       var == "Geo"~6,
                                       var == "Pseudo"~7,
                                       var == "Econ"~8,
                                       var == "Analyst"~9)) %>%
    dplyr::arrange(group_id, parameter) %>%
    dplyr::select(-group_id)
  
  df_right <- readRDS(paste0('../../tmp/covliquidity/', stock_base, '/pairwise_decom_table.Rds')) %>%
    dplyr::filter(micro == "yes",
                  name == "lev",
                  liq_measure == "volume",
                  part == "sym",
                  parameter != "t_per") %>%
    dplyr::select(-micro, -name, -liq_measure, -part) %>%
    dplyr::mutate(group_id = case_when(var == "combined"~1,
                                       var == "Indu"~2,
                                       var == "BEAcustomer"~3,
                                       var == "BEAsupplier"~4,
                                       var == "Tec"~5,
                                       var == "Geo"~6,
                                       var == "Pseudo"~7,
                                       var == "Econ"~8,
                                       var == "Analyst"~9)) %>%
    dplyr::arrange(group_id, parameter) %>%
    dplyr::select(-group_id)
  
  df.1 <- df_left %>%
    dplyr::inner_join(df_right, by = c("var", "parameter")) %>%
    dplyr::group_by(var) %>%
    dplyr::mutate(var = replace(var, row_number() != 1, NA)) %>%
    dplyr::ungroup()
  
  
  
  
  
  
  data_table <- df.1 %>%
    dplyr::select(-parameter)
  
  
  align_vactor <- paste0("ll", paste0(rep("c", times = dim(data_table)[2] - 1), collapse = ""))
  caption_name_15 <- paste0("Decompose $R'_{t+1}\\cdot\\Pi_t\\cdot R_{t}$ Based on Pairwise Liquidity Comparison")
  x.side <- xtable(data_table, align = align_vactor, caption = caption_name_15)
  cat("The stock base is:", stock_base)
  print(x.side, type = "latex", table.placement = "H", include.rownames = FALSE,
        include.colnames = FALSE, scalebox = 0.9,
            caption.placement = "top", #"top", NULL
            hline.after=NULL, #We don't need hline; we use booktabs
            floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
            sanitize.text.function = force , # Important to treat content of first column as latex function
             add.to.row = list(pos = list(-1,
                                            nrow(data_table)),
                               command = c(paste("\\hline \n",  # NEW row
                                                 "Liq measure:&\\multicolumn{5}{c}{\\textbf{Bid-ask spread}}
                                                 & \\multicolumn{5}{c}{\\textbf{Trading Volume}}
                                                 \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n",
                                                 " & All& Illiq$\\rightarrow$Liq & Self &Liq$\\rightarrow$illiq  & Diff & All& Illiq$\\rightarrow$Liq & Self & Liq$\\rightarrow$illiq & Diff  \\\\\n",
                                                 "& (1) & (2) & (3) & (4)& (5) & (6) & (7) & (8)& (9) & (10)  \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n"),
                   paste("\\hline \n"))
                   )
  )
  
  print(x.side, type = "latex", table.placement = "H", include.rownames = FALSE,
        include.colnames = FALSE, scalebox = 0.9,
            caption.placement = "top", #"top", NULL
            hline.after=NULL, #We don't need hline; we use booktabs
            floating=TRUE, # whether \begin{Table} should be created (TRUE) or not (FALSE)
            sanitize.text.function = force , # Important to treat content of first column as latex function
             add.to.row = list(pos = list(-1,
                                            nrow(data_table)),
                               command = c(paste("\\hline \n",  # NEW row
                                                 "Liq measure:&\\multicolumn{5}{c}{\\textbf{Bid-ask spread}}
                                                 & \\multicolumn{5}{c}{\\textbf{Trading Volume}}
                                                 \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n",
                                                 " & All& Illiq$\\rightarrow$Liq & Self &Liq$\\rightarrow$illiq  & Diff & All& Illiq$\\rightarrow$Liq & Self & Liq$\\rightarrow$illiq & Diff  \\\\\n",
                                                 "& (1) & (2) & (3) & (4)& (5) & (6) & (7) & (8)& (9) & (10)  \\\\\n", "\\cmidrule(l){2-6} \\cmidrule(l){7-11}\n"),
                   paste("\\hline \n"))
                   ),
        file = paste0(stock_base, "/liquid_illiquid_sym_lev_adjust.tex")
  )
}
```